// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHW_e7ouVnkJvCx8R9SFdtIj2rtPocJ-8',
    appId: '1:192514862611:web:e986624787f375c09519e6',
    messagingSenderId: '192514862611',
    projectId: 'hobby-b1c8b',
    authDomain: 'hobby-b1c8b.firebaseapp.com',
    storageBucket: 'hobby-b1c8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_rEjafNre7S0KmayIVpdITUmAc700Yxc',
    appId: '1:192514862611:android:8ba1914ae525d8e79519e6',
    messagingSenderId: '192514862611',
    projectId: 'hobby-b1c8b',
    storageBucket: 'hobby-b1c8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC88xPlF-SWstcfRb6XsQe8W2lI-auPCSQ',
    appId: '1:192514862611:ios:05146dec06f2a8d99519e6',
    messagingSenderId: '192514862611',
    projectId: 'hobby-b1c8b',
    storageBucket: 'hobby-b1c8b.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
